name: Push-to-EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # name: Deploy to EC2
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

